GX.LANGS = {
    1: {
        defaultSel: '- 선택 -',
        msg: {
            numSel: '사용할 수 없는 번호입니다.',
            weekSel: '차수를 선택하세요.',
            whSel: '창고를 선택하세요.',
            reasonSel: '사유를 선택하세요.',
            duplicate: '동일한 용기가 선택되었습니다.',
            del: '항목을 삭제하시겠습니까?',
            err: 'API에서 반환된 결과에 오류가 있습니다.',
            bottleNoChk : '입력된 용기번호가 없습니다.',
        },
        login: {
            title: '로그인',
            search: ['언어', '사업단위','아이디','비밀번호','아이디 저장'],
            button: ['로그인'],
        },
        main: {
            title: '메인',
            menu: ['생산공정', '물류관리', '용기관리'],
        },
        subMain: {
            pageUrls1:'생산공정',
            pageUrls2:'물류관리',
            pageUrls3:'용기관리',
        },
        materialsInput: {
            menu:'자재투입',
            title: '작업지시',
            search: ['일자', '워크센터'],
            button: ['저장'],
            column: ['품명', 'Lot No', '선택', '수량'],
        },
        processInformation: {
            title: '공정정보',
            search: [],
            button: ['선택'],
            column: ['공정코드', '공정명', '선택'],
        },
        inputItem: {
            title: '투입품목조회',
            search: ['지시번호'],
            button: ['선택'],
            column: ['품목코드', '품명', 'Select', 'LotNo', '기준수량'],
        },
        inputMaterialInfo: {
            title: '투입자재정보',
            search: ['기준수량', '투입수량'],
            button: ['저장'],
            column: ['LotNo', '입고일자', '재고', '투입'],
            msg: ['상/하한치를 초과한 데이터가 있습니다. 저장 하시겠습니까?', '입력된 투입 수량이 없습니다.'],
        },
        workOrder: {
            menu:'작업지시',
            title: '작업지시',
            search: ['일자', '워크센터'],
            button: ['저장'],
            column: ['품명', 'Lot No', '선택', '수량'],
        },
        workOrderPacking: {
            title: '포장품목 정보',
            search: ['품명'],
            button: ['저장'],
            column: ['삭제', '번호', '바코드', '수량'],
        },
        packingPerformance: {
            menu: '포장실적',
            title: '포장실적',
            search: ['일자', '위크센터'],
            button: ['저장'],
            column: ['품명', 'Lot No', '선택', '수량'],
        },
        packagingItemInfo: {
            title: '포장품목 정보',
            search: ['제품', '용기', '품명'],
            button: ['저장'],
            column: ['X', 'No', '용기번호', '포장수량'],
            msg: ['동일한 제품이 등록되어있습니다.', '동일한 용기가 등록되어있습니다.',
                '포장수량과 지시수량이 일치하지 않습니다.', '입력된 포장품목이 없습니다.'],
        },
        materialForwarding: {
            menu: '생산자재불출',
            title: '자재출고처리',
            search: ['일자', '요청번호', '출고창고'],
            button: ['저장'],
            column: ['삭제', '번호', '자재번호', '자재명', '수량', 'LotNo'],
        },
        materialTransfer: {
            menu: '자재이동',
            title: '자재이동',
            search: ['일자', '출고창고', '입고창고'],
            button: ['저장'],
            column: ['삭제', '번호', '자재번호', '자재명', '수량', 'LotNo'],
        },
        forwardingInfo: {
            menu: '출하완료',
            title: '출고정보',
            search: ['일자', '제품라벨', '요청번호', '출고창고'],
            button: ['저장'],
            column: ['삭제', '번호', '용기번호', '용기명', '수량', '제품명', 'LotNo'],
        },
        received: {
            menu: '입고완료',
            title: '입고완료',
            menu2: '세척완료',
            title2: '세척완료',
            search: ['일자', '창고'],
            button: ['저장'],
            column: ['삭제', '번호', '용기번호', '제품명'],
        },
        containerRepair: {
            menu: '용기수리',
            title: '용기수리',
            search: ['일자', '수리구분'],
            button: ['저장'],
            column: ['삭제', '번호', '바코드'],
        },
        containerMovement: {
            menu: '용기이동',
            title: '용기이동',
            search: ['일자', '이동구분', '출고창고', '입고창고'],
            button: ['저장'],
            column: ['삭제', '번호', '용기번호', '제품명'],
        },
        containerSale: {
            menu: '용기매각',
            title: '용기매각',
            search: ['일자', '창고'],
            button: ['저장'],
            column: ['품명', '수량', '선택'],
        },
        containerInfo: {
            title: '용기매각',
            search: [],
            button: ['저장'],
            column: ['삭제', '번호', '바코드'],
        },
        containerInspection: {
            menu: '용기실사',
            title: '용기실사',
            search: ['일자', '- 차주 -', '실사창고', '제품라벨', '실시사유'],
            button: ['저장'],
            column: ['삭제', '번호', '바코드'],
        },
    },
    2: {
        defaultSel: '- Select -',
        msg: {
            numSel: 'This number is not available.',
            weekSel: 'Please select a week.',
            whSel: 'Please select a warehouse.',
            reasonSel: 'Please select a reason.',
            duplicate: 'The same container has been selected.',
            del: 'Are you sure you want to delete the item?',
            err: 'There was an error in the results returned by the API.',
            bottleNoChk : 'No number entered.',
        },
        login: {//로그인
            title: 'login',
            search: ['language', 'Biz Unit','ID','Password','ID Save'],
            button: ['LOGIN'],
        },
        main: {
            title: 'MAIN',
            menu: ['Production Process', 'Inventory Control', 'Container Management'],
        },
        subMain: {
            pageUrls1:'Production Process',
            pageUrls2:'Inventory Control',
            pageUrls3:'Container Management',
        },
        materialsInput: {//자재투입
            menu:'Material Input',
            title: 'Work Order',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        processInformation: {//공정정보
            title: 'Process Information',
            search: [],
            button: ['Select'],
            column: ['Process Code', 'Process Name', 'Select'],
        },
        inputItem: {//투입품목조회
            title: 'Process Information',
            search: ['Instruction No.'],
            button: ['Select'],
            column: ['Item Code', 'Item Name', 'Select', 'LotNo', 'Standard UoM Qty'],
        },
        inputMaterialInfo: {//투입자재정보
            title: 'Input Material Information',
            search: ['Instruction No.', 'Input Qty'],
            button: ['Save'],
            column: ['LotNo', 'GR Date', 'Inventory', 'Input'],
            msg: ['There is data that exceeds the upper/lower limit. Do you want to save it?', 'No InputQty entered.'],
        },
        workOrder: {//작업지시
            menu:'Work Order',
            title: 'Work Order',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        workOrderPacking: {//포장품목 정보
            title: 'Packaging Item Information',
            search: ['Item Name'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode', 'Qty'],
        },
        packingPerformance: {//포장실적
            menu: 'Packing Performance',
            title: 'Packing Performance',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        packagingItemInfo: {//포장품목 정보
            title: 'Packaging Item Information',
            search: ['Product', 'Container', 'Item Name'],
            button: ['Save'],
            column: ['X', 'No', 'Container No.', 'Packing Qty'],
            msg: ['The same product is registered.', 'The same container is registered.',
                'The Packing Qty and Work Order Qty do not match.', 'No packaging item entered.'],
        },
        materialForwarding: {//생산자재불출
            menu: 'Production Material GI',
            title: 'Material GI Processing',
            search: ['Date', 'Request No.', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'LotNo'],
        },
        materialTransfer: {//자재이동
            menu: 'Material Stock Movement',
            title: 'Material Stock Movement',
            search: ['Date', 'GI W/H', 'GR W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'LotNo'],
        },
        forwardingInfo: {//출하완료
            menu: 'Shipment Completed',
            title: 'GI Info',
            search: ['Date', 'Label', 'Request No.', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'Product Name', 'LotNo'],
        },
        received: {//입고완료,세척완료
            menu: 'GR Complete',
            title: 'GR Complete',
            menu2: 'Wash Complete',
            title2: 'Wash Complete',
            search: ['Date', 'W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Container No.', 'Product Name'],
        },
        containerRepair: {//용기수리
            menu: 'Container Repair',
            title: 'Container Repair',
            search: ['Date', 'Repair'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
        containerMovement: {//용기이동
            menu: 'Container Movement',
            title: 'Container Movement',
            search: ['Date', 'Type', 'GI W/H', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Container No.', 'Product Name'],
        },
        containerSale: {//용기매각
            menu: 'Container Sale',
            title: 'Container Sale',
            search: ['Date', 'W/H'],
            button: ['Select'],
            column: ['Item Name', 'Qty', 'Select'],
        },
        containerInfo: {//용기매각 > 용기매각
            title: 'Container Sale',
            search: [],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
        containerInspection: {//용기실사
            menu: 'Courageous Due Diligence',
            title: 'Courageous Due Diligence',
            search: ['Date', '- Week -', 'Counting W/H', 'Label', 'Due Diligence'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
    },
}