GX.LANGS = {
    1: {
        defaultSel: '- 선택 -',
        msg: {
            numSel: '사용할 수 없는 번호입니다.',
            weekSel: '차수를 선택하세요.',
            whSel: '창고를 선택하세요.',
            reasonSel: '사유를 선택하세요.',
            duplicate: '동일한 용기가 선택되었습니다.',
            del: '항목을 삭제하시겠습니까?',
            err: 'API에서 반환된 결과에 오류가 있습니다.',
            bottleNoChk : '입력된 용기번호가 없습니다.',
        },
        login: {
            title: '로그인',
            search: ['언어', '사업단위','아이디','비밀번호','아이디 저장'],
            button: ['환경설정','로그인'],
        },
        setting: {
            title: '환경 설정',
            text: '네트워크 통신 환경을 설정합니다.\<br\>통신할 서버의 접속 정보를 입력하세요.',
            search: ['데이터 연결(DSN)', '언어', '서버주소', '서버선택'],
            button: ['저장하기'],
        },
        main: {
            title: '메인 메뉴',
            menu: ['제품출고처리', '구매납품입력', '자재출고처리', '자재출고처리(미계획분)', '재고실사등록', 'LOT재고실사내역조회'],
        },
        subMain: {
            pageUrls1:'생산공정',
            pageUrls2:'물류관리',
            pageUrls3:'용기관리',
        },
        productShipmentTargetInquiry:{
            title: '제품출고대상 조회 ',
            search: ['거래서명세일', '거래처', '납품서번호'],
            button: ['조회'],
            column: ['번호', '거래서명세일', '거래처', '납품서번호', '비고'],
        },
        productForwardingProcessing:{
            title: '제품출고처리',
            search: ['Lot No.'],
            button: ['출고처리(수량불일치)', '출고처리', '출고취소', '닫기'],
            column: ['번호', '품번', '수량', '스캔수량'],
        },

        purchaseOrderItemInquiry: {
            menu:'자재투입',
            title: '구매발주품목 조회',
            search: ['발주일', '거래처', '자재번호'],
            button: ['조회'],
            column: ['번호', '발주일', '거래처', '발주번호', '자재번호', '자재명', '규격', '수량'],
        },
        purchaseDeliveryProcessing: {
            title: '구매납품처리',
            search: ['발주일', '거래처', '자재번호', '자재명', '규격', '납품일', '수량', '입고창고', '거래처Lot No.'],
            button: ['납품처리'],
            column: ['공정코드', '공정명', '선택'],
        },

        materialForwardingRequestItemInquiry:{
            title: '자재출고요청품목 조회',
            search: ['요청일'],
            button: ['조회'],
            column: ['번호', '요청일', '워크센터', '자재번호', '자재명', '규격', '요청수량'],
        },
        materialForwardingProcessing:{
            title: '자재출고처리',
            search: ['Lot No.', '출고창고', '자재번호', '자재명', '규격', '출고일', '수량', '입고창고'],
            button: ['출고처리'],
            column: [],
        },
        materialForwardingProcessingUnplanned:{
            title: '자재출고처리(미계획분)',
            search: ['Lot No.', '출고창고', '자재번호', '자재명', '규격', '출고일', '수량', '입고창고'],
            button: ['출고처리'],
            column: [],
        },

        inventoryRegistration: {
            title: '재고실사등록',
            search: ['Lot No.', '품명', '품번', '규격', '처리일', '실사수량', '창고'],
            button: ['실사등록'],
            column: [],
            msg: [],
        },
        inventoryCountingDetailsInquiry: {
            title: 'LOT재고실사내역 조회',
            search: ['실사일'],
            button: ['조회'],
            column: ['번호', '실사일', '창고', '품번', '품명', '규격', '장부수량', '실사수량', '단위', 'Lot No.'],
        },


        
    },
    2: {
        defaultSel: '- Select -',
        msg: {
            numSel: 'This number is not available.',
            weekSel: 'Please select a week.',
            whSel: 'Please select a warehouse.',
            reasonSel: 'Please select a reason.',
            duplicate: 'The same container has been selected.',
            del: 'Are you sure you want to delete the item?',
            err: 'There was an error in the results returned by the API.',
            bottleNoChk : 'No number entered.',
        },
        login: {//로그인
            title: 'login',
            search: ['language', 'Biz Unit','ID','Password','ID Save'],
            button: ['LOGIN'],
        },
        main: {
            title: 'MAIN',
            menu: ['Production Process', 'Inventory Control', 'Container Management'],
        },
        subMain: {
            pageUrls1:'Production Process',
            pageUrls2:'Inventory Control',
            pageUrls3:'Container Management',
        },
        materialsInput: {//자재투입
            menu:'Material Input',
            title: 'Work Order',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        processInformation: {//공정정보
            title: 'Process Information',
            search: [],
            button: ['Select'],
            column: ['Process Code', 'Process Name', 'Select'],
        },
        inputItem: {//투입품목조회
            title: 'Process Information',
            search: ['Instruction No.'],
            button: ['Select'],
            column: ['Item Code', 'Item Name', 'Select', 'LotNo', 'Standard UoM Qty'],
        },
        inputMaterialInfo: {//투입자재정보
            title: 'Input Material Information',
            search: ['Instruction No.', 'Input Qty'],
            button: ['Save'],
            column: ['LotNo', 'GR Date', 'Inventory', 'Input'],
            msg: ['There is data that exceeds the upper/lower limit. Do you want to save it?', 'No InputQty entered.'],
        },
        workOrder: {//작업지시
            menu:'Work Order',
            title: 'Work Order',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        workOrderPacking: {//포장품목 정보
            title: 'Packaging Item Information',
            search: ['Item Name'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode', 'Qty'],
        },
        packingPerformance: {//포장실적
            menu: 'Packing Performance',
            title: 'Packing Performance',
            search: ['Date', 'Work Center'],
            button: ['Select'],
            column: ['Item Name', 'Lot No', 'Select', 'Qty'],
        },
        packagingItemInfo: {//포장품목 정보
            title: 'Packaging Item Information',
            search: ['Product', 'Container', 'Item Name'],
            button: ['Save'],
            column: ['X', 'No', 'Container No.', 'Packing Qty'],
            msg: ['The same product is registered.', 'The same container is registered.',
                'The Packing Qty and Work Order Qty do not match.', 'No packaging item entered.'],
        },
        materialForwarding: {//생산자재불출
            menu: 'Production Material GI',
            title: 'Material GI Processing',
            search: ['Date', 'Request No.', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'LotNo'],
        },
        materialTransfer: {//자재이동
            menu: 'Material Stock Movement',
            title: 'Material Stock Movement',
            search: ['Date', 'GI W/H', 'GR W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'LotNo'],
        },
        forwardingInfo: {//출하완료
            menu: 'Shipment Completed',
            title: 'GI Info',
            search: ['Date', 'Label', 'Request No.', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Material No.', 'Material Name', 'Qty', 'Product Name', 'LotNo'],
        },
        received: {//입고완료,세척완료
            menu: 'GR Complete',
            title: 'GR Complete',
            menu2: 'Wash Complete',
            title2: 'Wash Complete',
            search: ['Date', 'W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Container No.', 'Product Name'],
        },
        containerRepair: {//용기수리
            menu: 'Container Repair',
            title: 'Container Repair',
            search: ['Date', 'Repair'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
        containerMovement: {//용기이동
            menu: 'Container Movement',
            title: 'Container Movement',
            search: ['Date', 'Type', 'GI W/H', 'GI W/H'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Container No.', 'Product Name'],
        },
        containerSale: {//용기매각
            menu: 'Container Sale',
            title: 'Container Sale',
            search: ['Date', 'W/H'],
            button: ['Select'],
            column: ['Item Name', 'Qty', 'Select'],
        },
        containerInfo: {//용기매각 > 용기매각
            title: 'Container Sale',
            search: [],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
        containerInspection: {//용기실사
            menu: 'Courageous Due Diligence',
            title: 'Courageous Due Diligence',
            search: ['Date', '- Week -', 'Counting W/H', 'Label', 'Due Diligence'],
            button: ['Save'],
            column: ['Delete', 'No.', 'Barcode'],
        },
    },
}